<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net5.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <RootNamespace>MainApplication</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\MVVMCore\CommonUtils\CommonUtils\CommonUtils.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="Keysight.Ccl.Wsl">
      <HintPath>..\..\Component\Keysight\Keysight.Ccl.Wsl.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
